name: CI to practice

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'   

    - name: Install dependencies
      run: echo "npm ci"

    - name: Linting
      run: echo "npm run lint"

    - name: Typechecking
      run: echo "npm run typecheck" 

    - name: Run tests
      run: echo "npm run test:ci"
    